[Interface]
PrivateKey = 4OwleQgGeCNcIJ3W010rKZADIdHP/HgGquENcaGPnmk=
Address = 10.1.0.3/24
DNS = 10.1.0.2         

[Peer]
PublicKey = y/Up4Ps6jIdZHzOL2LDYnkZB3JL03MZtZmGLZXESr1U=
Endpoint = 138.199.203.38:51821
AllowedIPs = 10.1.0.0/24   
PersistentKeepalive = 25
