{ self, ... }: {
  flake.modules.nixos.asus = { modulesPath, lib, config, ... }: {
    
    # Generated by ‘nixos-generate-config’ 
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/2f43d004-c3ea-4785-83d9-7a72aefd0517";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/3BE1-2AEA";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/4b4d4b14-d51d-4a6e-a9b8-eae64c6f08de"; }
      ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; 
  };

  flake.modules.nixos.asus_kernel_crashes = { pkgs, ... }: {
    boot.kernelPackages = pkgs.linuxPackages_lts;

    boot.kernel.sysctl = {
      "kernel.panic" = 10;                   # Reboot 10 seconds after a panic
      "kernel.panic_on_oops" = 1;            # Panic immediately on an oops
      "kernel.hung_task_timeout_secs" = 120; # Trigger panic if a task hangs >2min
    };

    boot.extraModprobeConfig = ''
      options iwlwifi power_save=0 uapsd_disable=1
    '';
  };

  hosts.stroby-asus = {
    nixos.imports = with self.modules.nixos; [
      asus
      asus_kernel_crashes
      keep_on_with_closed_lid
      battery
      battery-server-notifications
      server
      cli
      cli-full
      postgres
    ];

    homeManager.imports = with self.modules.homeManager; [
      cli
      cli-full
    ];
  };
}
