{ self, ... }: {
  flake.modules.nixos.laptop = { modulesPath, lib, config, ... }: {

    # Generated by ‘nixos-generate-config’ 
    imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/d79b6505-387d-43f3-8a45-3acd6575ddd4";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/2060-1BF8";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices =
      [ { device = "/dev/disk/by-uuid/fbfbd2cd-0113-4644-8129-5eb992dcff6b"; }
      ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };


  hosts.stroby-laptop = {
    nixos.imports = with self.modules.nixos; [
        laptop
        framework
        fix_tpm2
        networking
        networking_vpn
        bluetooth
        battery
        syncthing
        fingerprint
        smb
        cli
        cli-full
        hyprland
        intel-graphics
        apps-minimal
        apps
        code
        projects_tauri
        #postgres
        #algo_trading
        games
        solaar
      ];

    homeManager = {
      imports = with self.modules.homeManager; [
        solaar
        cli
        cli-full
        hyprland
        battery-hyprland-notifications
        apps-minimal
        apps
        code
        solaar
      ];

      home.sessionVariables.terminal = "kitty";
    };
  };
}
