{ self, ... }: {
  flake.modules.nixos.pigman = { modulesPath, lib, config, ... }: {

    # Generated by ‘nixos-generate-config’ 
    imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/e503145c-0eae-4c84-9525-1afe7645f75b";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/AA45-AD03";
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp25s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;  
  };

  hosts.pigman = {
    nixos.imports = with self.modules.nixos; [
        pigman
        networking
        networking_vpn
        cli
      #cli-full
      #hyprland
      #apps-minimal
      #solaar
      ];

    homeManager = {
      imports = with self.modules.homeManager; [
        solaar
        cli
      #cli-full
      #hyprland
      #apps-minimal
      #solaar
      ];

      home.sessionVariables.terminal = "kitty";
    };
  };
}
